version: "3.8"

services:
  postgresdb:
    image: "postgres:16-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
